language: node_js
node_js:
  - "stable"
services:
  - postgresql 
cache:
  directories:
    - "node_modules"
before_script:
  - npm run db-migrate && npm run db-seed-all
after_script:
  - npm run db-undo-migrate
script:
  - npm run coveralls
