language: node_js
node_js:
  - "stable"
services:
  - postgresql 
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - npm test
after_success:
  - npm run coveralls
  - npm run coverage
  